### ISSUE TITLE
Buggy animation after adjusting PostLayoutListener

### ISSUE THREAD

**Issue by JGreenwood94** [Azoft/CarouselLayoutManager#14] opened 2016-08-25 13:22 UTC
Hi, after following the advice in the issue: https://github.com/Azoft/CarouselLayoutManager/issues/4 , and adjusting the zoom size and some of the spacing sizes and animation tends to jump around, especially when a carousel item settles at the centre point. Cheers

**Comment by azoft-dev-team** [comment] 2016-08-26 09:01
Hi, could you please provide your code?

**Comment by mig35** [comment] 2016-09-05 04:23
@JGreenwood94 any update here?

**Comment by nachtien** [comment] 2016-09-09 21:47
Hi!

I'm experiencing a similar issue.  I'm trying to fade all items that are not the center one away, after no interaction with the RecyclerView.   I have it almost working, minus one bug.  If you scroll really fast and then stop the scroll, the items animate, but then appear right away.  Do you have any suggestions?  

Here's my code:
`public class CarouselZoomPostLayoutListener implements CarouselLayoutManager.PostLayoutListener {

    @Override
    public ItemTransformation transformChild(@NonNull final View child, final float itemPositionToCenterDiff, final int orientation) {
        final float scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff) + 1.0) / Math.PI + 1));

        // because scaling will make view smaller in its center, then we should move this item to the top or bottom to make it visible
        final float translateY;
        final float translateX;
        if (CarouselLayoutManager.VERTICAL == orientation) {
            final float translateYGeneral = child.getMeasuredHeight() * (1 - scale) / 2f;
            translateY = Math.signum(itemPositionToCenterDiff) * translateYGeneral;
            translateX = 0;
        } else {
            final float translateXGeneral = child.getMeasuredWidth() * (1 - scale) / 2f;
            translateX = Math.signum(itemPositionToCenterDiff) * translateXGeneral;
            translateY = 0;
        }

        **if (itemPositionToCenterDiff == 0f) {
            child.clearAnimation();
            child.setAlpha(1f);
        } else {
            final Animation fadeOut = new AlphaAnimation(1, 0);
            fadeOut.setStartOffset(500);
            fadeOut.setDuration(500);
            fadeOut.setFillAfter(true);
            child.startAnimation(fadeOut);
        }**
        return new ItemTransformation(scale, scale, translateX, translateY);
    }
}`


Bonus question:  How do I get the scroll offset?

Thanks in advance for your help.

**Comment by mig35** [comment] 2016-11-11 03:52
Hi @nachtien.
Not sure if it late or not but..
I've checked your code and it is working fine except one thing: disappearing items if user stops his interaction.
You need to change your code to start animation only if itemPositionToCenterDiff is near an integer value. That means that main item is near its center position.
https://github.com/Azoft/CarouselLayoutManager/blob/master/resources/issues14.gif

**Comment by nachtien** [comment] 2016-11-11 03:55
Thanks! There is a callback for when the view is detached from the recycler
view which I used I stop the animations. It mitigated the problem
significantly but it still exists

**Comment by mig35** [comment] 2016-11-11 04:03
@nachtien can you send a sample project to mig35 at mig35.com and make animation of your problem? I have same time to fix it.
Thanks.

**Comment by nachtien** [comment] 2016-11-11 04:29
Ok I'll try to do that by next week. Thanks! 🙏

**Comment by mig35** [comment] 2016-11-18 06:48
@nachtien any update? :)

**Comment by nachtien** [comment] 2016-11-18 07:06
@mig35, woops, thanks for following up with me.  I've been so wrapped up with other works tasks that I had to put this to the side.  I'll try to get this to you tomorrow.  Thanks for following up with me again.  👍

**Comment by mig35** [comment] 2016-12-06 10:47
And again @nachtien  :)

**Comment by maxglu** [comment] 2016-12-06 15:10
Hi! I have the same issue with  animation luggs after first start carousel. After i see all items, all works smooth, but first launch seems terrible.

**Comment by nachtien** [comment] 2016-12-06 21:07
I'm gonna do this today @mig35!!

**Comment by nachtien** [comment] 2016-12-07 01:27
Ughhhhhhh, work is hectic and I didn't get around it :(.  We have another release coming up and I'm jam packed with things to do.  The logic above with the CarouselZoomPostLayoutListener is what I currently have been using, and then in the reyclerview, when the view is detached, I stop the animations on the view.

**Comment by nachtien** [comment] 2016-12-07 01:27
I really really appreciate you trying to help @mig35.

**Comment by nachtien** [comment] 2016-12-07 01:28
> You need to change your code to start animation only if itemPositionToCenterDiff is near an integer value. That means that main item is near its center position.

I actually did this too and the issue still happens.

**Comment by mig35** [comment] 2016-12-07 04:46
@nachtien could you post your code relative to this problem to my email? mig35 at mig35.com
In my apps and layouts I cannot see any difficulties. The only way is to fully reproduce your layout and code in recyclerview holder (activity/fragment), adapter and etc. So this is why I need you code in project.

**Comment by mig35** [comment] 2016-12-07 04:51
@maxglu first launch and later things shouldn't be different a lot. Are you sure this is issue of carousel? Do you do any other work on the MainThread?

After i see all items, all works smooth, but first launch seems terrible.
This sentence doesn't make sense carousel shows constant items count at the moment. And other elements are loaded from the recycler view using its cache, so there is no difference if you scroll it to see all the elements or not.

Please, post you animation somewhere or look through the previous post and send you buggy sample project to this email address.

**Comment by mig35** [comment] 2016-12-07 08:58
@maxglu I'll close this ticket because for @nachtien it was not carousel bug, but this was a bug in the custom PostLayoutListener.
If you feel that this is our bug, you can start new issue and post your problem description. And I'll be glad to help you.

**Closed by mig35** 2016-12-07 08:58 UTC

**Comment by sagarhudge** [comment] 2019-04-12 07:07
@azoft-dev-team 

When I am trying to scroll list the view in center position it looks like jumping to center position
in ItemTransformation transformChild method
`final float scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff) + 1.0) / Math.PI + 1));

    // because scaling will make view smaller in its center, then we should move this item to the top or bottom to make it visible
    final float translateY;
    final float translateX;
    if (CarouselLayoutManager.VERTICAL == orientation) {
        final float translateYGeneral = child.getMeasuredHeight() * (1 - scale) / 2f;
        translateY = Math.signum(itemPositionToCenterDiff) * translateYGeneral;
        translateX = 0;
    } else {
// final float translateXGeneral = child.getMeasuredWidth() * (1 - scale) / 2f;
final float translateXGeneral = child.getMeasuredWidth() * (0.9f - scale) / 1.7f;

        translateX = Math.signum(itemPositionToCenterDiff) * translateXGeneral;
        translateY = 0;
    }


    return new ItemTransformation(scale, scale, translateX, translateY);`

**Comment by sagarhudge** [comment] 2019-04-12 07:08
When I am trying to scroll list the view in center position it looks like jumping to center position
in ItemTransformation transformChild method
`final float scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff) + 1.0) / Math.PI + 1));
  // because scaling will make view smaller in its center, then we should move this item to the top or bottom to make it visible
    final float translateY;
    final float translateX;
    if (CarouselLayoutManager.VERTICAL == orientation) {
        final float translateYGeneral = child.getMeasuredHeight() * (1 - scale) / 2f;
        translateY = Math.signum(itemPositionToCenterDiff) * translateYGeneral;
        translateX = 0;
    } else {
// final float translateXGeneral = child.getMeasuredWidth() * (1 - scale) / 2f;
final float translateXGeneral = child.getMeasuredWidth() * (0.9f - scale) / 1.7f;

        translateX = Math.signum(itemPositionToCenterDiff) * translateXGeneral;
        translateY = 0;
    }
    return new ItemTransformation(scale, scale, translateX, translateY);`

**Comment by sagarhudge** [comment] 2019-04-12 07:09
When I am trying to scroll list the view in center position it looks like jumping to center position
in `ItemTransformation transformChild` method
`final float scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff) + 1.0) / Math.PI + 1));

        // because scaling will make view smaller in its center, then we should move this item to the top or bottom to make it visible
        final float translateY;
        final float translateX;
        if (CarouselLayoutManager.VERTICAL == orientation) {
            final float translateYGeneral = child.getMeasuredHeight() * (1 - scale) / 2f;
            translateY = Math.signum(itemPositionToCenterDiff) * translateYGeneral;
            translateX = 0;
        } else {
//            final float translateXGeneral = child.getMeasuredWidth() * (1 - scale) / 2f;
            final float translateXGeneral = child.getMeasuredWidth() * (0.9f - scale) / 1.7f;

            translateX = Math.signum(itemPositionToCenterDiff) * translateXGeneral;
            translateY = 0;
        }


        return new ItemTransformation(scale, scale, translateX, translateY);`

**Comment by sagarhudge** [comment] 2019-04-12 07:12
@azoft-dev-team @mig35 @JGreenwood94 

On list scroll, view in center position jumps to its position my transition code is as follow view size is `90dp`

` final float scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff) + 1.0) / Math.PI + 1));
        final float translateY;
        final float translateX;
        if (CarouselLayoutManager.VERTICAL == orientation) {
            final float translateYGeneral = child.getMeasuredHeight() * (1 - scale) / 2f;
            translateY = Math.signum(itemPositionToCenterDiff) * translateYGeneral;
            translateX = 0;
        } else {
//            final float translateXGeneral = child.getMeasuredWidth() * (1 - scale) / 2f;
            final float translateXGeneral = child.getMeasuredWidth() * (0.9f - scale) / 1.7f;
            translateX = Math.signum(itemPositionToCenterDiff) * translateXGeneral;
            translateY = 0;
        }
`

**Comment by sagarhudge** [comment] 2019-04-12 07:13
@azoft-dev-team @JGreenwood94  @mig35 @nachtien @maxglu 

On list scroll, view in center position jumps to its position my transition code is as follow view size is `90dp`

`final float scale = (float) (2 * (2 * -StrictMath.atan(Math.abs(itemPositionToCenterDiff) + 1.0) / Math.PI + 1));
        final float translateY;
        final float translateX;
        if (CarouselLayoutManager.VERTICAL == orientation) {
            final float translateYGeneral = child.getMeasuredHeight() * (1 - scale) / 2f;
            translateY = Math.signum(itemPositionToCenterDiff) * translateYGeneral;
            translateX = 0;
        } else {
            final float translateXGeneral = child.getMeasuredWidth() * (0.9f - scale) / 1.7f;
            translateX = Math.signum(itemPositionToCenterDiff) * translateXGeneral;
            translateY = 0;
        }
        return new ItemTransformation(scale, scale, translateX, translateY);`
